"""Recruitment-specific prompts for ad copy generation (Stage 3).

Copy is generated by Gemma 3 12B in the contributor's native language.
Every piece of copy follows the OneForma contributor recruitment tone:
friendly, opportunity-focused, concrete benefits, never corporate.

Each platform returns the EXACT fields, character limits, and CTA options
that the real ad platform expects --- no generic headline/body fallback.
"""
from __future__ import annotations

import json
from typing import Any

from prompts.ethical_positioning import (
    apply_ethical_framing,
    build_ethical_copy_prompt,
    detect_sensitivity,
)
from prompts.persona_engine import build_persona_copy_prompt

# ---------------------------------------------------------------------------
# Re-export ethical helpers so existing imports still work.
# ---------------------------------------------------------------------------
__all__ = [
    "COPY_SYSTEM_PROMPT",
    "COPY_EVAL_SYSTEM_PROMPT",
    "PLATFORM_AD_SPECS",
    "MARKETING_PSYCHOLOGY",
    "build_copy_prompt",
    "build_copy_eval_prompt",
    "build_persona_targeted_copy_prompt",
    "select_psychology_hooks",
    "apply_ethical_framing",
    "detect_sensitivity",
]

# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

COPY_SYSTEM_PROMPT = (
    "You are an elite multilingual copywriter for OneForma recruitment ads.\n\n"
    "OneForma recruits data annotation contributors worldwide — students, "
    "freelancers, stay-at-home parents, and multilingual professionals.\n\n"
    "Your copy must:\n"
    "- Sound like a friend telling you about a great opportunity — NOT like a corporation hiring\n"
    "- Lead with SPECIFIC numbers: dollar amounts, timeframes, contributor counts\n"
    "- Address the persona's #1 pain point in the FIRST line\n"
    "- Weave in the persona's trigger words naturally\n"
    "- Use the target language natively (not translated-sounding)\n"
    "- Use LOCAL CURRENCY for non-US markets (R$ for Brazil, ₹ for India, etc)\n"
    "- Be platform-appropriate in BOTH tone AND field structure\n"
    "- Return the EXACT JSON fields the target platform requires\n"
    "- Respect every character limit — count carefully\n\n"
    "WORDS THAT CONVERT (use these):\n"
    "- Specific dollar amounts: '$12/hr', 'R$60/hr', '$500/mo'\n"
    "- Local payment methods: 'Pix', 'PayPal', 'Payoneer'\n"
    "- 'Paid weekly' / 'Paid every Friday' (NOT 'weekly payouts')\n"
    "- 'No experience needed' / 'Just your language skills'\n"
    "- 'Work from your phone' / 'Work from anywhere'\n"
    "- '50,000+ contributors' / 'Join 50K+'\n"
    "- 'Get your first task in 24 hours' / 'Apply in 2 Minutes'\n"
    "- Task clarity: 'Review AI translations', 'Rate chatbot responses'\n"
    "- Question openers: 'Speak Portuguese?', 'Bilingual?'\n\n"
    "STOP USING THESE (proven failures):\n"
    "- 'Human review' / 'secure payments' / 'secure platform' — jargon\n"
    "- 'Powered by Centific' — zero brand recognition\n"
    "- 'Flexible hours' — every gig platform says this\n"
    "- 'Start earning' without a number — empty promise\n"
    "- 'Skip the commute' — outdated post-COVID\n"
    "- 'Extra income' without quantifying — too vague\n"
    "- 'We are hiring' / 'Position available' — corporate HR speak\n"
    "- 'Learn More' / 'Sign Up' / 'Join Now' — generic CTA"
)

COPY_EVAL_SYSTEM_PROMPT = (
    "You evaluate recruitment ad copy for OneForma. Score each dimension "
    "0.0 to 1.0. Focus on whether the copy would make a real person in "
    "the target region stop scrolling and consider signing up. Also verify "
    "that the copy contains the EXACT fields required by the target "
    "platform and that every field is within its character limit."
)

# ---------------------------------------------------------------------------
# PLATFORM_AD_SPECS — real platform fields, limits, CTAs, tone, and examples
# ---------------------------------------------------------------------------

PLATFORM_AD_SPECS: dict[str, dict[str, Any]] = {
    # ----- Meta (Facebook/Instagram) Feed Ads -----
    "facebook_feed": {
        "fields": {
            "primary_text": "Main body text above the image — this is where the story/hook lives.",
            "headline": "Bold text below the image.",
            "description": "Gray text below headline.",
            "cta_button": "One of the allowed CTA values.",
            "display_link": "Short display URL shown to user.",
        },
        "char_limits": {
            "primary_text": {"recommended": 125, "max": 2200},
            "headline": {"recommended": 27, "max": 40},
            "description": {"recommended": 27, "max": 30},
            "display_link": {"max": 30},
        },
        "cta_options": [
            "APPLY_NOW", "LEARN_MORE", "SIGN_UP",
            "GET_OFFER", "CONTACT_US", "SUBSCRIBE",
        ],
        "tone": (
            "Casual, friendly, scroll-stopping — like a friend's post. "
            "Emoji use is fine. Short sentences. Lead with benefit or question."
        ),
        "good_examples": [
            "Earn $15/hr from your couch — just use your language skills",
            "Your phone. Your schedule. Real money. 🎯",
            "500K+ people already earn with OneForma. You in?",
        ],
        "bad_examples": [
            "We are hiring data annotators for our AI platform",
            "OneForma is looking for qualified candidates to join our team",
            "Position: Data Annotation Specialist — Competitive Salary",
        ],
        "psychology_hooks": [
            "social_proof", "curiosity_gap", "identity_appeal",
        ],
    },

    # ----- Meta Stories/Reels Ads -----
    "facebook_stories": {
        "fields": {
            "primary_text": "Overlay text on the creative — ultra-short.",
            "cta_button": "One of the allowed CTA values.",
            "sticker_text": "Optional — short label like 'Hiring Now' or 'Flexible Work'.",
        },
        "char_limits": {
            "primary_text": {"max": 72},
            "sticker_text": {"max": 25},
        },
        "cta_options": ["SWIPE_UP", "LEARN_MORE", "SIGN_UP", "APPLY_NOW"],
        "tone": (
            "Ultra-short, punchy, visual-first. "
            "One sentence max. Emojis are encouraged. Feels native to Stories."
        ),
        "good_examples": [
            "Your language = 💰. Swipe up.",
            "Earn from home. No degree needed.",
            "Flexible AI work. Start today 🚀",
        ],
        "bad_examples": [
            "OneForma offers competitive compensation for data annotation",
            "We are seeking contributors for our growing platform",
            "Apply now for exciting opportunities in AI",
        ],
        "psychology_hooks": [
            "effort_minimization", "loss_aversion", "curiosity_gap",
        ],
    },

    # ----- LinkedIn Sponsored Content -----
    "linkedin_feed": {
        "fields": {
            "introductory_text": "Professional tone — appears above image. Mobile-optimized.",
            "headline": "Bold text below image.",
            "description": "Supporting text below headline.",
            "cta_button": "One of the allowed CTA values.",
            "organization_name": "Always 'OneForma by Centific'.",
        },
        "char_limits": {
            "introductory_text": {"recommended": 150, "max": 600},
            "headline": {"max": 70},
            "description": {"max": 100},
        },
        "cta_options": [
            "APPLY", "LEARN_MORE", "SIGN_UP",
            "REGISTER", "SUBSCRIBE", "DOWNLOAD",
        ],
        "tone": (
            "Professional but warm — like a colleague sharing an opportunity. "
            "No emojis. Career-growth language. Acknowledge the reader's expertise."
        ),
        "good_examples": [
            "Your multilingual skills have real value in the AI economy",
            "Remote AI work that fits around your career",
            "Join 500K+ professionals shaping the future of AI",
        ],
        "bad_examples": [
            "🔥 HOT JOB ALERT 🔥 We're hiring!!!",
            "Gig work from home!! Easy money!!",
            "OneForma is disrupting the AI data annotation space",
        ],
        "psychology_hooks": [
            "identity_appeal", "social_proof", "concrete_specificity",
        ],
    },

    # ----- TikTok In-Feed Ads -----
    "tiktok_feed": {
        "fields": {
            "ad_text": "Appears at bottom of video. Casual, Gen-Z friendly.",
            "cta_button": "One of the allowed CTA values.",
            "display_name": "Always '@OneForma'.",
            "profile_text": "Short description visible on profile tap.",
        },
        "char_limits": {
            "ad_text": {"max": 100},
            "display_name": {"max": 20},
            "profile_text": {"max": 80},
        },
        "cta_options": [
            "LEARN_MORE", "SIGN_UP", "APPLY_NOW",
            "DOWNLOAD", "CONTACT_US",
        ],
        "tone": (
            "Gen-Z friendly, emoji-ok, trendy. Speak like a creator, not a brand. "
            "Use internet slang sparingly. Short, punchy, relatable."
        ),
        "good_examples": [
            "POV: you get paid for speaking your language 💸",
            "No resume. No interview. Just vibes and your skills.",
            "Side hustle that actually pays — link in bio",
        ],
        "bad_examples": [
            "Apply for data annotation opportunities at OneForma",
            "We offer flexible remote work in the AI industry",
            "Competitive rates for qualified linguists and annotators",
        ],
        "psychology_hooks": [
            "curiosity_gap", "effort_minimization", "social_proof",
        ],
    },

    # ----- Telegram Sponsored Messages -----
    "telegram_card": {
        "fields": {
            "message_text": "Direct, conversational. No images — text only.",
            "button_text": "Single CTA button label.",
            "button_url": "Landing page URL.",
        },
        "char_limits": {
            "message_text": {"max": 160},
            "button_text": {"max": 20},
            "button_url": {"max": 100},
        },
        "cta_options": [],  # Free-form button text — no fixed list.
        "tone": (
            "Direct, community-oriented — like a group admin sharing something useful. "
            "No fluff. Get to the point. Conversational but not slangy."
        ),
        "good_examples": [
            "Speak another language? OneForma pays you to use it. Remote, flexible, real money.",
            "AI companies need human judgment. OneForma pays for yours. No degree required.",
            "500K people earn with OneForma. Flexible hours, real pay, join from anywhere.",
        ],
        "bad_examples": [
            "Dear potential contributor, we invite you to explore opportunities",
            "OneForma is a leading data annotation platform seeking talent",
            "Click here to learn more about our exciting positions",
        ],
        "psychology_hooks": [
            "social_proof", "loss_aversion", "concrete_specificity",
        ],
    },

    # ----- Google Display Ads (Responsive) -----
    "google_display": {
        "fields": {
            "headlines": "3-5 short headlines (30 chars each). Google mixes and matches.",
            "long_headline": "Used in larger placements.",
            "descriptions": "2-3 descriptions (90 chars each).",
            "business_name": "Always 'OneForma'.",
            "cta_text": "Optional — only if CTA extension is enabled.",
        },
        "char_limits": {
            "headlines": {"max_per_item": 30, "min_count": 3, "max_count": 5},
            "long_headline": {"max": 90},
            "descriptions": {"max_per_item": 90, "min_count": 2, "max_count": 3},
        },
        "cta_options": [],  # CTA via extension — free-form if enabled.
        "tone": (
            "Concise, benefit-led, high-contrast. Every character counts. "
            "No filler words. Specific numbers beat vague claims."
        ),
        "good_examples": [
            "Earn $15/hr From Home",
            "AI Work — No Degree Needed",
            "Flexible Remote AI Tasks",
        ],
        "bad_examples": [
            "OneForma Data Annotation",
            "Click Here For More Info",
            "Great Opportunity Inside",
        ],
        "psychology_hooks": [
            "concrete_specificity", "effort_minimization", "identity_appeal",
        ],
    },

    # ----- Indeed Sponsored Jobs -----
    "indeed_banner": {
        "fields": {
            "job_title": "Specific and searchable. Not a marketing headline.",
            "company_description": "What OneForma does — for job seekers.",
            "job_highlights": "Up to 3 bullet points.",
            "salary_info": "Optional — rate range if available.",
            "location_type": "Usually 'Remote'.",
        },
        "char_limits": {
            "job_title": {"max": 60},
            "company_description": {"max": 200},
            "job_highlights": {"max_per_item": 50, "max_count": 3},
        },
        "cta_options": [],  # Indeed uses its own Apply button.
        "tone": (
            "Job-seeker empathetic — acknowledge their search. Professional but "
            "human. Specific about what the work is. Honest about flexibility."
        ),
        "good_examples": [
            "Remote Data Annotator — AI Training ($12-18/hr)",
            "Freelance Multilingual AI Evaluator — Flexible Hours",
            "Remote AI Content Reviewer — No Degree Required",
        ],
        "bad_examples": [
            "Amazing AI Opportunity!!!",
            "Work From Home — Easy Money",
            "Data Entry Specialist (this misrepresents the work)",
        ],
        "psychology_hooks": [
            "concrete_specificity", "identity_appeal", "effort_minimization",
        ],
    },

    # ----- X (Twitter) Promoted Ads -----
    "twitter_post": {
        "fields": {
            "tweet_text": "Conversational, hashtag-friendly. The main post.",
            "card_headline": "Website card headline.",
            "card_description": "Website card description.",
            "cta": "Inherits from tweet intent — not a fixed button.",
        },
        "char_limits": {
            "tweet_text": {"max": 280},
            "card_headline": {"max": 70},
            "card_description": {"max": 200},
        },
        "cta_options": [],  # No fixed CTA list — inherits from tweet intent.
        "tone": (
            "Witty, conversational, hashtaggable. Speak like a person, not a brand. "
            "Threads-friendly. Hot takes welcome. Engage, don't announce."
        ),
        "good_examples": [
            "Your language skills are worth more than you think. AI companies are paying $15/hr for human judgment. No resume needed.",
            "Imagine getting paid to scroll — but in another language. That's basically what OneForma contributors do.",
            "Hot take: your bilingual brain is an AI superpower. OneForma pays for it. #RemoteWork #SideHustle",
        ],
        "bad_examples": [
            "OneForma is now hiring! Visit our website to apply.",
            "We're looking for talented individuals to join our team!",
            "Exciting career opportunity in the field of AI data annotation.",
        ],
        "psychology_hooks": [
            "curiosity_gap", "identity_appeal", "social_proof",
        ],
    },
}

# Backward-compatible alias for imports that reference the old name.
PLATFORM_GUIDANCE = PLATFORM_AD_SPECS


# ---------------------------------------------------------------------------
# MARKETING_PSYCHOLOGY — hooks and templates for copy generation
# ---------------------------------------------------------------------------

MARKETING_PSYCHOLOGY: dict[str, dict[str, Any]] = {
    "social_proof": {
        "description": "People follow what others do",
        "templates": [
            "Join {number}+ contributors already earning",
            "{number} people in {region} signed up this month",
            "Trusted by {number}+ contributors worldwide",
        ],
        "best_for": ["facebook_feed", "linkedin_feed", "telegram_card"],
    },
    "curiosity_gap": {
        "description": "Open a loop the reader needs to close",
        "templates": [
            "The reason {number} people quit their 9-5 for this...",
            "What if your {language} skills were worth $15/hr?",
            "You won't believe what AI companies pay for {language}...",
        ],
        "best_for": ["tiktok_feed", "facebook_feed", "twitter_post"],
    },
    "loss_aversion": {
        "description": "Fear of missing out is stronger than desire to gain",
        "templates": [
            "Your {language} skills are in demand right now — don't wait",
            "This project closes in {days} days",
            "Spots are filling fast for {language} speakers",
        ],
        "best_for": ["facebook_stories", "telegram_card"],
    },
    "concrete_specificity": {
        "description": "Specific numbers are more believable than vague claims",
        "templates": [
            "Earn ${rate}/hr annotating {task_type} from home",
            "{hours}hrs/week, {rate}/hr, 100% remote",
            "${rate}/hr — {task_type} tasks — start this week",
        ],
        "best_for": ["google_display", "indeed_banner", "linkedin_feed"],
    },
    "identity_appeal": {
        "description": "People act consistently with their identity",
        "templates": [
            "If you speak {language}, you're exactly who AI needs",
            "Data annotation: the job made for detail-oriented people like you",
            "Bilingual? Your brain is an AI superpower.",
        ],
        "best_for": ["linkedin_feed", "facebook_feed"],
    },
    "effort_minimization": {
        "description": "Reduce perceived effort to start",
        "templates": [
            "Sign up in 2 minutes. Start earning today.",
            "No degree. No interview. Just your skills.",
            "Apply once, get matched to projects automatically.",
        ],
        "best_for": ["tiktok_feed", "google_display", "facebook_stories"],
    },
}


# ---------------------------------------------------------------------------
# select_psychology_hooks — pick the best hooks for a channel + brief
# ---------------------------------------------------------------------------

def select_psychology_hooks(
    channel: str,
    brief: dict,
    *,
    max_hooks: int = 3,
) -> list[dict[str, Any]]:
    """Select the most effective psychology hooks for a channel and brief.

    Parameters
    ----------
    channel:
        The ad platform key (e.g. ``"facebook_feed"``).
    brief:
        The creative brief dict — used to pick hooks whose templates
        can be meaningfully populated (e.g. if brief contains a rate,
        ``concrete_specificity`` is prioritised).
    max_hooks:
        Maximum number of hooks to return (default 3).

    Returns
    -------
    list[dict]
        Each dict contains ``name``, ``description``, ``templates``, and a
        ``relevance`` note explaining why this hook was selected.
    """
    brief_text = json.dumps(brief, ensure_ascii=False, default=str).lower()

    # Score each hook by (a) platform fit and (b) template fillability.
    scored: list[tuple[float, str, dict]] = []

    for hook_name, hook in MARKETING_PSYCHOLOGY.items():
        score = 0.0

        # Primary signal: is this hook recommended for the channel?
        if channel in hook.get("best_for", []):
            score += 2.0

        # Secondary signal: can the templates be filled from the brief?
        fillable_keywords = {
            "rate": ["rate", "pay", "earn", "salary", "compensation", "$/hr"],
            "language": ["language", "lingual", "speak"],
            "number": ["contributor", "500", "1000", "people"],
            "region": ["region", "country", "location", "geo"],
            "task_type": ["task", "annotation", "review", "evaluation"],
            "days": ["deadline", "close", "days", "urgent"],
            "hours": ["hours", "part-time", "flexible"],
        }
        for _placeholder, keywords in fillable_keywords.items():
            if any(kw in brief_text for kw in keywords):
                score += 0.5

        relevance = (
            f"Recommended for {channel}"
            if channel in hook.get("best_for", [])
            else "Cross-platform effective"
        )

        scored.append((score, hook_name, {
            "name": hook_name,
            "description": hook["description"],
            "templates": hook["templates"],
            "relevance": relevance,
        }))

    # Sort descending by score, take top N.
    scored.sort(key=lambda t: t[0], reverse=True)
    return [item[2] for item in scored[:max_hooks]]


# ---------------------------------------------------------------------------
# _build_platform_json_schema — generate the expected JSON structure for a
# platform so Gemma 3 knows exactly what to return.
# ---------------------------------------------------------------------------

def _build_platform_json_schema(channel: str, language: str) -> str:
    """Return a JSON template string showing the exact fields Gemma 3 must
    return for *channel*, with inline char-limit comments."""
    spec = PLATFORM_AD_SPECS.get(channel, PLATFORM_AD_SPECS["facebook_feed"])
    limits = spec["char_limits"]

    if channel == "facebook_feed":
        return (
            '{{\n'
            f'  "primary_text": "<{limits["primary_text"]["recommended"]} chars recommended, '
            f'{limits["primary_text"]["max"]} max — the main body text in {language}>",\n'
            f'  "headline": "<{limits["headline"]["recommended"]} chars recommended, '
            f'{limits["headline"]["max"]} max — bold text below image in {language}>",\n'
            f'  "description": "<{limits["description"]["recommended"]} chars recommended, '
            f'{limits["description"]["max"]} max — gray text below headline in {language}>",\n'
            f'  "cta_button": "One of: {", ".join(spec["cta_options"])}",\n'
            '  "display_link": "oneforma.com/earn"\n'
            '}}'
        )
    elif channel == "facebook_stories":
        return (
            '{{\n'
            f'  "primary_text": "<{limits["primary_text"]["max"]} chars max — overlay text in {language}>",\n'
            f'  "cta_button": "One of: {", ".join(spec["cta_options"])}",\n'
            f'  "sticker_text": "<{limits["sticker_text"]["max"]} chars max — optional short label>"\n'
            '}}'
        )
    elif channel == "linkedin_feed":
        return (
            '{{\n'
            f'  "introductory_text": "<{limits["introductory_text"]["recommended"]} chars recommended, '
            f'{limits["introductory_text"]["max"]} max — professional text above image in {language}>",\n'
            f'  "headline": "<{limits["headline"]["max"]} chars max — bold text below image in {language}>",\n'
            f'  "description": "<{limits["description"]["max"]} chars max — supporting text in {language}>",\n'
            f'  "cta_button": "One of: {", ".join(spec["cta_options"])}",\n'
            '  "organization_name": "OneForma by Centific"\n'
            '}}'
        )
    elif channel == "tiktok_feed":
        return (
            '{{\n'
            f'  "ad_text": "<{limits["ad_text"]["max"]} chars max — bottom-of-video text in {language}>",\n'
            f'  "cta_button": "One of: {", ".join(spec["cta_options"])}",\n'
            '  "display_name": "@OneForma",\n'
            f'  "profile_text": "<{limits["profile_text"]["max"]} chars max — profile description in {language}>"\n'
            '}}'
        )
    elif channel == "telegram_card":
        return (
            '{{\n'
            f'  "message_text": "<{limits["message_text"]["max"]} chars max — direct message text in {language}>",\n'
            f'  "button_text": "<{limits["button_text"]["max"]} chars max — CTA button label in {language}>",\n'
            '  "button_url": "oneforma.com/join"\n'
            '}}'
        )
    elif channel == "google_display":
        return (
            '{{\n'
            f'  "headlines": ["<{limits["headlines"]["max_per_item"]} chars max each — '
            f'provide {limits["headlines"]["min_count"]}-{limits["headlines"]["max_count"]} headlines in {language}>"],\n'
            f'  "long_headline": "<{limits["long_headline"]["max"]} chars max — used in larger placements in {language}>",\n'
            f'  "descriptions": ["<{limits["descriptions"]["max_per_item"]} chars max each — '
            f'provide {limits["descriptions"]["min_count"]}-{limits["descriptions"]["max_count"]} descriptions in {language}>"],\n'
            '  "business_name": "OneForma",\n'
            f'  "cta_text": "<optional — short CTA if extension is enabled>"\n'
            '}}'
        )
    elif channel == "indeed_banner":
        return (
            '{{\n'
            f'  "job_title": "<{limits["job_title"]["max"]} chars max — specific, searchable title in {language}>",\n'
            f'  "company_description": "<{limits["company_description"]["max"]} chars max — what OneForma does>",\n'
            f'  "job_highlights": ["<{limits["job_highlights"]["max_per_item"]} chars max each — '
            f'up to {limits["job_highlights"]["max_count"]} bullet points in {language}>"],\n'
            '  "salary_info": "<optional — rate range>",\n'
            '  "location_type": "Remote"\n'
            '}}'
        )
    elif channel == "twitter_post":
        return (
            '{{\n'
            f'  "tweet_text": "<{limits["tweet_text"]["max"]} chars max — conversational post in {language}>",\n'
            f'  "card_headline": "<{limits["card_headline"]["max"]} chars max — website card headline in {language}>",\n'
            f'  "card_description": "<{limits["card_description"]["max"]} chars max — website card description in {language}>",\n'
            '  "cta": "<inherits from tweet intent>"\n'
            '}}'
        )
    else:
        # Fallback: facebook_feed structure.
        return _build_platform_json_schema("facebook_feed", language)


# ---------------------------------------------------------------------------
# build_copy_prompt — platform-specific prompt for Gemma 3
# ---------------------------------------------------------------------------

def build_copy_prompt(
    brief: dict,
    channel: str,
    language: str,
    regions: list[str] | None = None,
    form_data: dict | None = None,
    feedback: list | None = None,
) -> str:
    """Build the prompt for generating ad copy for a specific channel + language.

    The prompt instructs Gemma 3 to return the EXACT JSON fields the target
    platform requires, with per-field character limits and allowed CTAs.

    When the brief or form data touches sensitive categories (children's data,
    medical records, content moderation, etc.), ethical positioning guardrails
    are automatically injected into the prompt.
    """
    spec = PLATFORM_AD_SPECS.get(channel, PLATFORM_AD_SPECS["facebook_feed"])
    regions_str = ", ".join(regions) if regions else "Global"

    # --- Feedback from previous attempts ---
    feedback_section = ""
    if feedback:
        items = "\n".join(f"- {f}" for f in feedback)
        feedback_section = (
            f"\n\nPREVIOUS ATTEMPT FEEDBACK (address every point):\n{items}"
        )

    # --- Task details ---
    task_info = ""
    if form_data:
        task_info = f"\nTASK DETAILS: {json.dumps(form_data, ensure_ascii=False, default=str)}"

    # --- Ethical positioning: detect sensitive categories and inject framing ---
    sensitivity_input: dict = {**brief}
    if form_data:
        sensitivity_input["form_data"] = form_data
    detected_categories = detect_sensitivity(sensitivity_input)
    ethical_section = build_ethical_copy_prompt(brief, detected_categories)

    # --- Psychology hooks ---
    hooks = select_psychology_hooks(channel, brief)
    psychology_section = _format_psychology_section(hooks)

    # --- Platform-specific JSON schema ---
    json_schema = _build_platform_json_schema(channel, language)

    # --- Good / bad examples ---
    good_examples = "\n".join(f'- "{ex}"' for ex in spec.get("good_examples", []))
    bad_examples = "\n".join(f'- "{ex}"' for ex in spec.get("bad_examples", []))

    # --- CTA guidance ---
    cta_section = ""
    if spec["cta_options"]:
        cta_list = ", ".join(spec["cta_options"])
        cta_section = (
            f"\nALLOWED CTA VALUES (use EXACTLY one of these): {cta_list}"
        )
    else:
        cta_section = "\nCTA: Free-form text — write a short, compelling CTA."

    # --- Character limits summary ---
    limits_lines = []
    for field_name, limit_info in spec["char_limits"].items():
        if isinstance(limit_info, dict):
            if "max_per_item" in limit_info:
                count_range = f"{limit_info.get('min_count', 1)}-{limit_info.get('max_count', 5)}"
                limits_lines.append(
                    f"- {field_name}: {limit_info['max_per_item']} chars max per item, "
                    f"provide {count_range} items"
                )
            elif "recommended" in limit_info:
                limits_lines.append(
                    f"- {field_name}: {limit_info['recommended']} chars recommended, "
                    f"{limit_info['max']} max"
                )
            else:
                limits_lines.append(f"- {field_name}: {limit_info['max']} chars max")
    char_limits_block = "\n".join(limits_lines)

    return f"""Write recruitment ad copy for OneForma.

BRIEF:
{json.dumps(brief, indent=2, ensure_ascii=False, default=str)}

PLATFORM: {channel}
LANGUAGE: {language}
TARGET REGIONS: {regions_str}{task_info}

PLATFORM RULES:
Tone: {spec["tone"]}
{char_limits_block}
{cta_section}

{psychology_section}

Write ALL copy in {language}. It must sound native — not translated.

Return ONLY valid JSON with the EXACT fields shown below — no extra fields, no missing fields:
{json_schema}

EXAMPLES OF GOOD ONEFORMA COPY FOR {channel.upper()}:
{good_examples}

NEVER write (these are BAD examples):
{bad_examples}

NEVER write:
- "We are hiring" / "Job opening" / "Position available"
- "Competitive salary" / "Great benefits" / corporate HR language
- Generic motivational quotes
- Anything that sounds like it came from a corporate careers page{ethical_section}{feedback_section}"""


def _format_psychology_section(hooks: list[dict[str, Any]]) -> str:
    """Format selected psychology hooks into prompt instructions."""
    if not hooks:
        return ""

    lines = [
        "MARKETING PSYCHOLOGY — use these techniques in your copy:",
    ]
    for hook in hooks:
        lines.append(f"\n• {hook['name'].upper()}: {hook['description']}")
        lines.append(f"  Relevance: {hook['relevance']}")
        lines.append("  Example templates:")
        for template in hook["templates"]:
            lines.append(f"    - \"{template}\"")

    lines.append(
        "\nAdapt these techniques naturally — do NOT copy templates verbatim. "
        "Blend 1-2 hooks into your copy so it feels organic, not formulaic."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# build_copy_eval_prompt — platform-specific evaluation
# ---------------------------------------------------------------------------

def build_copy_eval_prompt(
    copy_data: dict,
    brief: dict,
    channel: str,
    language: str,
) -> str:
    """Build the prompt for evaluating generated ad copy.

    The evaluation checks that the copy contains the EXACT fields required
    by the target platform and that every field is within its character limit.
    """
    spec = PLATFORM_AD_SPECS.get(channel, PLATFORM_AD_SPECS["facebook_feed"])

    # Build a human-readable field checklist.
    field_checklist_lines = []
    for field_name, field_desc in spec["fields"].items():
        limit_info = spec["char_limits"].get(field_name)
        if limit_info:
            if isinstance(limit_info, dict) and "max_per_item" in limit_info:
                limit_str = (
                    f"{limit_info['max_per_item']} chars max per item, "
                    f"{limit_info.get('min_count', 1)}-{limit_info.get('max_count', 5)} items"
                )
            elif isinstance(limit_info, dict) and "recommended" in limit_info:
                limit_str = (
                    f"{limit_info['recommended']} chars recommended, "
                    f"{limit_info['max']} max"
                )
            elif isinstance(limit_info, dict):
                limit_str = f"{limit_info['max']} chars max"
            else:
                limit_str = str(limit_info)
        else:
            limit_str = "no char limit"
        field_checklist_lines.append(
            f"  - {field_name}: {field_desc} ({limit_str})"
        )
    field_checklist = "\n".join(field_checklist_lines)

    # CTA validation guidance.
    cta_validation = ""
    if spec["cta_options"]:
        cta_list = ", ".join(spec["cta_options"])
        cta_validation = (
            f"\nCTA VALIDATION: The CTA field must be EXACTLY one of: {cta_list}. "
            "Score cta_strength 0.0 if it uses an invalid value."
        )

    return f"""Evaluate this recruitment ad copy for OneForma.

COPY:
{json.dumps(copy_data, indent=2, ensure_ascii=False, default=str)}

BRIEF CONTEXT:
{json.dumps(brief, indent=2, ensure_ascii=False, default=str)}

PLATFORM: {channel}
LANGUAGE: {language}

REQUIRED FIELDS FOR {channel.upper()}:
{field_checklist}
{cta_validation}

Score each dimension 0.0 to 1.0:

- scroll_stopping: Would this make someone stop scrolling? Is it specific, surprising, or benefit-led?
- native_language: Does it sound like a native {language} speaker wrote it? No awkward translations?
- benefit_clarity: Are the benefits concrete and specific (not vague promises)?
- cta_strength: Is the CTA clear, action-oriented, and from the platform's allowed list?
- platform_fit: Does the tone and length match {channel} conventions?
- brand_voice: Does it match OneForma's friendly, opportunity-focused voice?
- character_compliance: Are ALL fields within platform character limits? Score 0.0 if ANY field exceeds its max.
- field_compliance: Are ALL required fields present? Score 0.0 if any required field is missing.

Return ONLY valid JSON:
{{
  "overall_score": 0.0,
  "dimensions": {{
    "scroll_stopping": {{"score": 0.0, "feedback": "..."}},
    "native_language": {{"score": 0.0, "feedback": "..."}},
    "benefit_clarity": {{"score": 0.0, "feedback": "..."}},
    "cta_strength": {{"score": 0.0, "feedback": "..."}},
    "platform_fit": {{"score": 0.0, "feedback": "..."}},
    "brand_voice": {{"score": 0.0, "feedback": "..."}},
    "character_compliance": {{"score": 0.0, "feedback": "..."}},
    "field_compliance": {{"score": 0.0, "feedback": "..."}}
  }},
  "field_char_counts": {{
    "<field_name>": "<actual_count>/<limit>"
  }},
  "improvement_suggestions": ["...", "..."]
}}"""


# ---------------------------------------------------------------------------
# build_persona_targeted_copy_prompt — combines persona context with
# the standard platform copy prompt for persona-specific ad copy.
# ---------------------------------------------------------------------------

def build_persona_targeted_copy_prompt(
    persona: dict,
    brief: dict,
    channel: str,
    language: str,
    regions: list[str] | None = None,
    form_data: dict | None = None,
    feedback: list | None = None,
) -> str:
    """Build a copy prompt that targets a specific persona.

    This wraps the standard ``build_copy_prompt`` with persona context
    prepended, so the LLM generates copy tailored to the persona's
    psychology, pain points, and motivations rather than a generic audience.

    Parameters
    ----------
    persona:
        A customised persona dict from the persona engine.
    brief:
        The creative brief dict.
    channel:
        The ad platform key (e.g. ``"facebook_feed"``).
    language:
        Target language for the copy.
    regions:
        Target regions.
    form_data:
        Task details from the intake form.
    feedback:
        Optional improvement suggestions from a failed evaluation.

    Returns
    -------
    str
        The full copy-generation prompt with persona context prepended.
    """
    # Generate the persona-specific context block.
    persona_block = build_persona_copy_prompt(persona, channel, language, brief)

    # Generate the standard platform copy prompt.
    standard_prompt = build_copy_prompt(
        brief=brief,
        channel=channel,
        language=language,
        regions=regions,
        form_data=form_data,
        feedback=feedback,
    )

    # Combine: persona context first, then the standard prompt.
    return f"""{persona_block}
---

{standard_prompt}"""


# ---------------------------------------------------------------------------
# 3-variation copy generation — angles derived from persona psychology
# ---------------------------------------------------------------------------

def extract_available_facts(brief: dict, form_data: dict | None = None) -> dict[str, str]:
    """Extract concrete facts from brief/form_data that the LLM can use.

    Returns a dict of fact_name → value. Only includes facts that actually
    exist — never fabricates. The LLM decides whether to use each fact.
    """
    facts: dict[str, str] = {}
    fd = form_data or {}

    # Compensation — check multiple possible locations
    comp = fd.get("compensation", brief.get("compensation", {}))
    if isinstance(comp, dict):
        rate = comp.get("rate", comp.get("hourly_rate", comp.get("pay_rate", "")))
        if rate:
            facts["rate"] = str(rate)
        currency = comp.get("currency", "")
        if currency:
            facts["currency"] = currency
        pay_method = comp.get("payment_method", comp.get("pay_method", ""))
        if pay_method:
            facts["payment_method"] = pay_method
    elif isinstance(comp, str) and comp:
        facts["compensation_description"] = comp

    # Simple rate field
    for key in ("rate", "pay_rate", "hourly_rate"):
        val = fd.get(key, brief.get(key, ""))
        if val and "rate" not in facts:
            facts["rate"] = str(val)

    # Task type
    task = fd.get("task_type", brief.get("task_type", ""))
    if task:
        facts["task_type"] = str(task).replace("_", " ")

    # Task description
    desc = fd.get("task_description", fd.get("description", ""))
    if desc:
        facts["task_description"] = str(desc)[:200]

    # Contributor count (if known)
    for key in ("contributor_count", "contributors", "community_size"):
        val = brief.get(key, fd.get(key, ""))
        if val:
            facts["contributor_count"] = str(val)

    # Target languages
    langs = brief.get("content_language", {})
    if isinstance(langs, dict) and langs.get("primary"):
        facts["primary_language"] = langs["primary"]

    # Regions
    regions = fd.get("target_regions", brief.get("target_regions", []))
    if regions:
        facts["regions"] = ", ".join(regions) if isinstance(regions, list) else str(regions)

    return facts


PEER_VOICE_SYSTEM = """You are NOT a copywriter. You are NOT a brand.

You are {persona_name}'s friend — someone their age, from their region, who just discovered OneForma and is genuinely excited to tell them about it.

You know {persona_name}'s situation: {lifestyle_snippet}
You know what keeps them up at night: {pain_snippet}
You know what would change their life: {motivation_snippet}

When you write ad copy, it should sound like a voice note or text to {persona_name} — real, specific, urgent but not desperate. You're sharing an opportunity you KNOW fits their life.

Rules:
- Write in {language}. It must sound native, not translated.
- Use the persona's trigger words naturally: {trigger_words}
- Address their #1 fear without being heavy-handed
- Be specific (if you have numbers, use them; if not, be specific about the EXPERIENCE instead)
- Return ONLY the JSON fields requested — no commentary
- Every word must earn its place. If a word could appear in any competitor's ad, cut it.

{copy_benchmarks}"""


COPY_BENCHMARKS_BLOCK = """
WORDS/PATTERNS THAT CONVERT (use when relevant, not forced):
- Specific amounts when available (local currency preferred)
- Local payment methods by market (Pix, PayPal, Payoneer)
- "No experience needed" / "Just your language skills"
- "Work from your phone" / "from anywhere"
- Contributor counts if known
- Time-to-start ("first task in 24 hours")
- Task clarity ("Review AI translations")
- Question openers ("Speak [language]?")

PATTERNS THAT KILL CONVERSION (never use):
- "Human review" / "secure payments" — internal jargon
- "Flexible hours" — every gig platform says this
- "Extra income" without specifics — empty
- "We are hiring" / "Position available" — corporate HR
- "Learn More" / "Sign Up" — generic CTA
- "Powered by Centific" — zero audience recognition
"""


def build_peer_voice_system(persona: dict, language: str) -> str:
    """Build a system prompt where the LLM embodies the persona's peer.

    The voice is calibrated from the persona's actual psychology — not
    hardwired to any fixed tone or angle.
    """
    psychology = persona.get("psychology_profile", {})
    trigger_words = psychology.get("trigger_words", [])

    return PEER_VOICE_SYSTEM.format(
        persona_name=persona.get("persona_name", persona.get("name", "this person")),
        lifestyle_snippet=persona.get("lifestyle", "their daily life")[:120],
        pain_snippet=persona.get("customized_pain", persona.get("pain_points", ["finding good opportunities"])[0] if persona.get("pain_points") else "")[:120],
        motivation_snippet=persona.get("customized_motivation", "a better opportunity")[:120],
        language=language,
        trigger_words=", ".join(trigger_words[:6]) if trigger_words else "authenticity, real talk",
        copy_benchmarks=COPY_BENCHMARKS_BLOCK,
    )


def build_variation_prompts(
    persona: dict,
    brief: dict,
    channel: str,
    language: str,
    regions: list[str] | None = None,
    form_data: dict | None = None,
) -> list[dict[str, str]]:
    """Build 3 copy prompts — one per psychological angle — derived from
    the persona's own psychology profile.

    Returns a list of 3 dicts, each with:
      - ``angle``: human-readable label for the variation
      - ``bias``: the psychology bias driving this angle
      - ``system``: the system prompt (peer voice)
      - ``user``: the user prompt (platform spec + angle instruction)

    The angles are NOT hardwired. They come from:
      1. persona.psychology_profile.primary_bias
      2. persona.psychology_profile.secondary_bias
      3. A contrasting "discovery" angle the LLM chooses
    """
    psychology = persona.get("psychology_profile", {})
    primary_bias = psychology.get("primary_bias", "")
    secondary_bias = psychology.get("secondary_bias", "")
    messaging_angle = psychology.get("messaging_angle", "")

    # Extract available facts (only what exists — no fabrication)
    facts = extract_available_facts(brief, form_data)
    facts_block = ""
    if facts:
        lines = [f"- {k}: {v}" for k, v in facts.items()]
        facts_block = (
            "\nAVAILABLE FACTS (use these if they fit your angle — do NOT fabricate data):\n"
            + "\n".join(lines)
        )

    # Build the base platform prompt (char limits, JSON schema, examples)
    base_prompt = build_copy_prompt(
        brief=brief,
        channel=channel,
        language=language,
        regions=regions,
        form_data=form_data,
    )

    # Persona context block
    from prompts.persona_engine import build_persona_copy_prompt
    persona_block = build_persona_copy_prompt(persona, channel, language, brief)

    # System prompt — peer voice
    system = build_peer_voice_system(persona, language)

    variations = []

    # ── Variation A: Primary psychology bias ──
    variations.append({
        "angle": f"primary_{primary_bias}" if primary_bias else "primary",
        "bias": primary_bias,
        "system": system,
        "user": f"""COPY ANGLE: Lead with {persona.get('persona_name', 'this person')}'s PRIMARY psychology — {primary_bias}.
Messaging direction: {messaging_angle}
{facts_block}

{persona_block}
---
{base_prompt}""",
    })

    # ── Variation B: Secondary psychology bias ──
    if secondary_bias and secondary_bias != primary_bias:
        variations.append({
            "angle": f"secondary_{secondary_bias}",
            "bias": secondary_bias,
            "system": system,
            "user": f"""COPY ANGLE: Lead with {persona.get('persona_name', 'this person')}'s SECONDARY psychology — {secondary_bias}.
This is a DIFFERENT angle from the primary ({primary_bias}). The tone, hook, and emotional trigger should feel distinctly different.
{facts_block}

{persona_block}
---
{base_prompt}""",
        })

    # ── Variation C: Discovery / Contrasting angle ──
    # The LLM picks an angle that NEITHER matches primary nor secondary
    variations.append({
        "angle": "discovery",
        "bias": "contrasting",
        "system": system,
        "user": f"""COPY ANGLE: SURPRISE ME. Write copy using a psychology angle that is NEITHER {primary_bias} nor {secondary_bias}.
Pick whichever angle you believe will resonate most with {persona.get('persona_name', 'this person')} based on their profile — but it MUST be a fundamentally different hook from the other two variations.
Consider: curiosity gap, loss aversion, identity appeal, effort minimization, social belonging, aspirational storytelling, or any angle that fits.
{facts_block}

{persona_block}
---
{base_prompt}""",
    })

    return variations
