"""Recruitment-specific prompts for ad copy generation (Stage 3).

Copy is generated by Gemma 3 12B in the contributor's native language.
Every piece of copy follows the OneForma contributor recruitment tone:
friendly, opportunity-focused, concrete benefits, never corporate.
"""

COPY_SYSTEM_PROMPT = (
    "You are a multilingual copywriter for OneForma recruitment ads.\n\n"
    "OneForma recruits data annotation contributors worldwide — students, "
    "freelancers, stay-at-home parents, and multilingual professionals.\n\n"
    "Your copy must:\n"
    "- Sound like a friend telling you about a great opportunity\n"
    "- Lead with concrete benefits (earnings, flexibility, skills)\n"
    "- Use the target language natively (not translated-sounding)\n"
    "- Be platform-appropriate (LinkedIn = professional, Facebook = casual, "
    "Telegram = direct, Indeed = job-seeker focused)\n"
    "- Include a clear call-to-action with an action verb\n"
    "- NEVER use corporate jargon, buzzwords, or 'We are hiring' language"
)

COPY_EVAL_SYSTEM_PROMPT = (
    "You evaluate recruitment ad copy for OneForma. Score each dimension "
    "0.0 to 1.0. Focus on whether the copy would make a real person in "
    "the target region stop scrolling and consider signing up."
)

# Platform-specific character limits and tone guidance.
PLATFORM_GUIDANCE: dict[str, dict] = {
    "linkedin_feed": {
        "headline_max": 60,
        "body_max": 150,
        "tone": "professional but warm — like a colleague sharing an opportunity",
        "cta_style": "action-oriented, career-focused",
    },
    "facebook_feed": {
        "headline_max": 40,
        "body_max": 125,
        "tone": "casual, friendly, scroll-stopping — like a friend's post",
        "cta_style": "informal, benefit-first",
    },
    "facebook_stories": {
        "headline_max": 30,
        "body_max": 0,
        "tone": "ultra-short, punchy, visual-first",
        "cta_style": "swipe-up style, one action verb",
    },
    "telegram_card": {
        "headline_max": 50,
        "body_max": 200,
        "tone": "direct, community-oriented — like a group admin",
        "cta_style": "join/start now",
    },
    "indeed_banner": {
        "headline_max": 50,
        "body_max": 120,
        "tone": "job-seeker empathetic — acknowledge their search",
        "cta_style": "apply-focused, immediate",
    },
    "google_display": {
        "headline_max": 30,
        "body_max": 90,
        "tone": "concise, benefit-led, high-contrast",
        "cta_style": "short action phrase",
    },
    "tiktok_feed": {
        "headline_max": 35,
        "body_max": 0,
        "tone": "Gen-Z friendly, emoji-ok, trendy",
        "cta_style": "tap/try now",
    },
    "twitter_post": {
        "headline_max": 50,
        "body_max": 200,
        "tone": "witty, conversational, hashtaggable",
        "cta_style": "link-click focused",
    },
}


def build_copy_prompt(
    brief: dict,
    channel: str,
    language: str,
    regions: list[str] | None = None,
    form_data: dict | None = None,
    feedback: list | None = None,
) -> str:
    """Build the prompt for generating ad copy for a specific channel + language."""
    import json

    guidance = PLATFORM_GUIDANCE.get(channel, PLATFORM_GUIDANCE["facebook_feed"])
    regions_str = ", ".join(regions) if regions else "Global"

    feedback_section = ""
    if feedback:
        items = "\n".join(f"- {f}" for f in feedback)
        feedback_section = (
            f"\n\nPREVIOUS ATTEMPT FEEDBACK (address every point):\n{items}"
        )

    task_info = ""
    if form_data:
        task_info = f"\nTASK DETAILS: {json.dumps(form_data, ensure_ascii=False)}"

    return f"""Write recruitment ad copy for OneForma.

BRIEF:
{json.dumps(brief, indent=2, ensure_ascii=False)}

PLATFORM: {channel}
LANGUAGE: {language}
TARGET REGIONS: {regions_str}{task_info}

PLATFORM RULES:
- Headline: max {guidance["headline_max"]} characters
- Body text: max {guidance["body_max"]} characters (0 = no body, headline only)
- Tone: {guidance["tone"]}
- CTA style: {guidance["cta_style"]}

Write ALL copy in {language}. It must sound native — not translated.

Return ONLY valid JSON:
{{
  "headline": "The main headline in {language}",
  "subheadline": "Optional subheadline (leave empty if platform has no body)",
  "body": "Body text if the platform supports it",
  "cta_text": "Call-to-action button text in {language}",
  "hashtags": ["optional", "hashtags", "if platform supports them"],
  "language": "{language}",
  "platform": "{channel}",
  "character_counts": {{
    "headline": 0,
    "body": 0,
    "cta": 0
  }}
}}

EXAMPLES OF GOOD ONEFORMA HEADLINES:
- "Earn $15/hr from your couch — just use your {language} skills"
- "Your phone. Your schedule. Real money."
- "AI companies need YOUR language. Start earning today."
- "Flexible work that actually pays. No degree needed."
- "Turn your downtime into income — join 500K+ contributors"

NEVER write:
- "We are hiring" / "Job opening" / "Position available"
- "Competitive salary" / "Great benefits" / corporate HR language
- Generic motivational quotes
- Anything that sounds like it came from a corporate careers page{feedback_section}"""


def build_copy_eval_prompt(
    copy_data: dict,
    brief: dict,
    channel: str,
    language: str,
) -> str:
    """Build the prompt for evaluating generated ad copy."""
    import json

    guidance = PLATFORM_GUIDANCE.get(channel, PLATFORM_GUIDANCE["facebook_feed"])

    return f"""Evaluate this recruitment ad copy for OneForma.

COPY:
{json.dumps(copy_data, indent=2, ensure_ascii=False)}

BRIEF CONTEXT:
{json.dumps(brief, indent=2, ensure_ascii=False)}

PLATFORM: {channel}
LANGUAGE: {language}
HEADLINE MAX: {guidance["headline_max"]} chars
BODY MAX: {guidance["body_max"]} chars

Score each dimension 0.0 to 1.0:

- scroll_stopping: Would this make someone stop scrolling? Is it specific, surprising, or benefit-led?
- native_language: Does it sound like a native {language} speaker wrote it? No awkward translations?
- benefit_clarity: Are the benefits concrete and specific (not vague promises)?
- cta_strength: Is the CTA clear, action-oriented, and compelling?
- platform_fit: Does the tone and length match {channel} conventions?
- brand_voice: Does it match OneForma's friendly, opportunity-focused voice?
- character_compliance: Are headline and body within platform limits?

Return ONLY valid JSON:
{{
  "overall_score": 0.0,
  "dimensions": {{
    "scroll_stopping": {{"score": 0.0, "feedback": "..."}},
    "native_language": {{"score": 0.0, "feedback": "..."}},
    "benefit_clarity": {{"score": 0.0, "feedback": "..."}},
    "cta_strength": {{"score": 0.0, "feedback": "..."}},
    "platform_fit": {{"score": 0.0, "feedback": "..."}},
    "brand_voice": {{"score": 0.0, "feedback": "..."}},
    "character_compliance": {{"score": 0.0, "feedback": "..."}}
  }},
  "improvement_suggestions": ["...", "..."]
}}"""
