"""Landing page template renderer — Jinja2.

Loads HTML templates, injects hard facts + generated copy + image URLs,
returns a complete self-contained HTML string ready for Vercel Blob upload.

Hard facts are injected as template variables — never generated by the LLM.
Generated copy fills the informational sections (why, activities, FAQ).
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent
TEMPLATE_MAP: dict[str, str] = {
    "dark_gradient": "lp_dark_gradient.html",
    # Future templates (Phase 2):
    # "fullbleed_photo": "lp_fullbleed_photo.html",
    # "split_screen": "lp_split_screen.html",
    # "minimal_editorial": "lp_minimal_editorial.html",
    # "card_grid": "lp_card_grid.html",
}

_env = Environment(
    loader=FileSystemLoader(str(TEMPLATES_DIR)),
    autoescape=select_autoescape(["html"]),
)


# ── Icon mapping ──────────────────────────────────────────────────────

ICON_MAP: dict[str, str] = {
    "users": "i-users",
    "smile": "i-smile",
    "spark": "i-spark",
    "globe": "i-globe",
    "shield": "i-shield",
    "book": "i-book",
    "video": "i-video",
    "mic": "i-mic",
    "dollar": "i-dollar",
    "pin": "i-pin",
    "cal": "i-cal",
    "clock": "i-clock",
    "lock": "i-lock",
    "check": "i-check",
}


def resolve_icon(hint: str) -> str:
    """Resolve an icon hint to an SVG symbol ID."""
    return ICON_MAP.get(hint.lower().strip(), "i-spark")


def select_template(task_type: str, persona: dict[str, Any]) -> str:
    """Select the best template variant based on task type + persona.

    Phase 1: always dark_gradient (the approved wireframe).
    Phase 2: use task_type + persona archetype to pick from 5 variants.
    """
    return "dark_gradient"


def render_landing_page(
    template_key: str,
    hard_facts: dict[str, Any],
    generated_copy: dict[str, Any],
    hero_copy: dict[str, Any],
    image_urls: dict[str, Any],
) -> str:
    """Render a landing page template with all variables injected.

    Parameters
    ----------
    template_key:
        Key from TEMPLATE_MAP (e.g., "dark_gradient").
    hard_facts:
        Injected verbatim — compensation, qualifications, locations, URLs.
        These are NEVER generated by the LLM.
    generated_copy:
        From Gemma 4 — why_cards, activities, session_details, faq.
    hero_copy:
        From Stage 3 — hero_h1, hero_subtitle, cta_text, hero_badge.
    image_urls:
        hero_image_url, actor_images list.

    Returns
    -------
    str
        Complete self-contained HTML string ready for blob upload.
    """
    template_file = TEMPLATE_MAP.get(template_key)
    if not template_file:
        raise ValueError(f"Unknown template key: {template_key!r}")

    template = _env.get_template(template_file)

    # Resolve icon hints in generated copy
    why_cards = generated_copy.get("why_cards", [])
    for card in why_cards:
        card["icon_id"] = resolve_icon(card.get("icon_hint", "spark"))

    activities = generated_copy.get("activities", [])

    # Merge all variables into one context dict
    context: dict[str, Any] = {
        # Hard facts
        **hard_facts,
        # Generated copy sections
        "why_cards": why_cards,
        "activities": activities,
        "session_details": generated_copy.get("session_details", []),
        "faq": generated_copy.get("faq", []),
        "meta_description": generated_copy.get("meta_description", ""),
        # Hero copy from Stage 3
        **hero_copy,
        # Image URLs
        **image_urls,
        # Utilities
        "resolve_icon": resolve_icon,
    }

    html = template.render(**context)
    logger.info(
        "Rendered LP template '%s': %d chars, %d why cards, %d activities, %d FAQ",
        template_key,
        len(html),
        len(why_cards),
        len(activities),
        len(generated_copy.get("faq", [])),
    )
    return html
